version: '3.8'

services:
  frontend:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8501
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8502:8501" 
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  llm-service:
    build: 
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network

  airflow-scheduler:
    image: apache/airflow:2.7.3
    restart: always
    depends_on:
      - postgres
      - redis
      - backend
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION='true'
      - AIRFLOW__CORE__LOAD_EXAMPLES='false'
      - BACKEND_URL=http://backend:8501
    volumes:
      - ./dags:/opt/airflow/dags
      - ./backend:/opt/airflow/backend
      - ./scraper:/opt/airflow/scraper
    networks:
      - app-network

  airflow-webserver:
    image: apache/airflow:2.7.3
    restart: always
    depends_on:
      - airflow-scheduler
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION='true'
      - AIRFLOW__CORE__LOAD_EXAMPLES='false'
      - BACKEND_URL=http://backend:8501
    volumes:
      - ./dags:/opt/airflow/dags
      - ./backend:/opt/airflow/backend
      - ./scraper:/opt/airflow/scraper
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db-volume: